
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: family_tree_db
      POSTGRES_USER: family_tree_user
      POSTGRES_PASSWORD: family_tree_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U family_tree_user -d family_tree_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - family-tree-network

  api:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      # Override DATABASE_URL for container networking
      - DATABASE_URL=postgresql+asyncpg://family_tree_user:family_tree_password@db:5432/family_tree_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - api_uploads:/app/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - family-tree-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  api_uploads:
    driver: local

networks:
  family-tree-network:
    driver: bridge