version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: family_tree_db
      POSTGRES_USER: family_tree_user
      POSTGRES_PASSWORD: family_tree_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U family_tree_user -d family_tree_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://family_tree_user:family_tree_password@db:5432/family_tree_db
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ORACLE_NAMESPACE=your-oracle-namespace
      - ORACLE_BUCKET_NAME=family-tree-files
      - ORACLE_ACCESS_KEY=your-access-key
      - ORACLE_SECRET_KEY=your-secret-key
      - ORACLE_REGION=us-ashburn-1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: